fix: minor issue
Hector-Network/hector-contracts pull request #50
Opened 2022-12-02 13:23 UTC by bejaxer

2022-12-02 13:23 UTC, bejaxer commented
![Result](https://user-images.githubusercontent.com/37297413/205302475-102e9696-f97c-469e-8050-fac9240192ca.png)

2022-12-02 14:40 UTC, michaelnguyen102 requested changes

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> -        uint256 fund = tokenBalances[_principal][fundRecipient];
@bejaxer what's the reason to remove this check?

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> +        tokenBalances[_principal][fundRecipient] = tokenBalances[_principal][
@bejaxer isn't this the same as tokenBalances[_principal][fundRecipient] += _amount.sub(fee);?

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> +                tokenBalances[_principal][feeRecipients[i]] = tokenBalances[
@bejaxer isn't this line doing the same thing as the deleted line?

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> +contract HectorBondV2NoTreasuryFTMDepository is
@bejaxer Will you change the contract name to BondNoTreasury? 
- Rename HectorBondV2NoTreasuryFTMDepository.sol to BondNoTreasury.sol

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> +contract HectorBondV2NoTreasuryFTMDepository is
Add a string public variable called version = "2.0"

2022-12-02 14:40 UTC, michaelnguyen102 commented on bond-no-treasury/contracts/HectorBondV2NoTreasuryFTMDepository.sol
> -        uint256 fee = tokenBalances[_principal][feeRecipient];
@bejaxer what's the reason behind removing this check?

2022-12-03 02:18 UTC, michaelnguyen102 approved these changes

2022-12-03 03:31 UTC, merged