Fix/bridge
Hector-Network/hector-contracts pull request #74
Opened 2023-06-05 21:21 UTC by michaelnguyen102

2023-06-06 15:16 UTC, bejaxer requested changes

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +			require(msg.value < totalAmounts + bridgeFees, 'Invalid payable value');
I am not sure what it is

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +			(bool success, ) = payable(DAO).call{value: feeAmounts}('');
`if (msg.value < totalAmounts +bridgeFees) revert; `

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
>  	) external payable {
Need to add the `whenNotPaused` modifier

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +		minFeePercentage = _feePercentage;
`require(minFeePercentage > 0 && minFeePercentage < 1000)`

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	function setVersion(string memory _version) external onlyOwner {
replace the `memory` to the `calldata`

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
Implement the `pause` and `unpause` ownerable function

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	function getWhiteListSize() public view returns (uint256) {
replace the `public` to the `external`

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	function getWhiteListAtIndex(uint256 index) public view returns (address) {
replace the `public` to the `external`

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	function addToWhiteList(address _callAddress) external onlyOwner {
Please reorder the contract functions

2023-06-06 15:16 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	using SafeMathUpgradeable for uint256;
is there any need to use the `SafeMath` library?

2023-06-08 14:24 UTC, michaelnguyen102 commented on bridge/contracts/HecBridgeSplitter.sol
> +	// Receive asset
@xiangdev1016 we may want to add a withdraw func for admin to withdraw tokens which may get stuck in this bridge contract when the bridge fails for some unexpected reason. You can use something like this https://github.com/Hector-Network/hector-contracts/blob/befa2e472db7462bf29e4aa92dd880cb8b9353c5/pay/contracts/subscription/HectorSubscriptionTreasury.sol#L62

2023-06-08 15:17 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +	using SafeMathUpgradeable for uint256;
@xiangdev1016, as we are using solidity v0.8.0+, there's no need to use the SafeMath
Also, you are not using the add(), sub(), mul(), div() functions on the existing contract
So you can remove it

2023-06-08 15:21 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +				(bool success, bytes memory result) = payable(callTargetAddress).call{value: fee}(callData);
@xiangdev1016, userA is going to swap 1000 FTM through the LiFi bridge and its fee is 10 FTM
In this case, how much FTM should be sent to the `callTargetAddress`?
1010 or 10?

2023-06-08 15:24 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +			(bool success, ) = payable(DAO).call{value: feeAmounts}('');
> Resolved
@xiangdev1016 
I cannot see the resolved code
???

2023-06-08 15:38 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +			(bool success, ) = payable(DAO).call{value: feeAmounts}('');
well... @xiangdev1016 , I mean if the asset == address(0)

2023-06-08 15:39 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +				(bool success, bytes memory result) = payable(callTargetAddress).call{value: fee}(callData);
> @xiangdev1016, userA is going to swap 1000 FTM through the LiFi bridge and its fee is 10 FTM In this case, how much FTM should be sent to the `callTargetAddress`? 1010 or 10?

@michaelnguyen102, would you please check it?
I think, we have to send `bridgeFee + sendingAmount` to the callTargetAddress when bridge the native coins

2023-06-08 15:57 UTC, bejaxer requested changes

2023-06-08 15:57 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +		if (msg.value < bridgeFees) revert INVALID_FEES();
There's no need to consider the `feeAmounts` when sendingAsset == address(0)

2023-06-08 15:58 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +				(bool success, bytes memory result) = payable(callTargetAddress).call{value: fee}(callData);
If the bridgeFee is including the sendingAmount, then it would be fine

2023-06-08 16:13 UTC, bejaxer commented on bridge/contracts/HecBridgeSplitter.sol
> +		if (msg.value < bridgeFees) revert INVALID_FEES();
so when sendingAsset == address(0), the `msg.value` should be greater than the `bridgeFees + feeAmounts`, shouldn't it?

2023-06-09 14:36 UTC, merged